# Generated by Django 5.0.2 on 2025-11-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, help_text='Course/Program of study', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.CharField(blank=True, help_text='e.g., 1st Year, 2nd Year', max_length=50),
        ),
    ]
