# Generated by Django 5.0.2 on 2025-11-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_course_department_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL for contact'),
        ),
    ]
