# Generated by Django 5.0.2 on 2025-11-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_survey_surveyresponse_surveysection_surveyquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='email_validation',
            field=models.CharField(choices=[('none', 'No Validation'), ('gmail', 'Gmail Only'), ('university', 'University Email Only'), ('both', 'Gmail or University Email')], default='both', help_text='Email validation requirement for student emails', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='require_property_info',
            field=models.BooleanField(default=True, help_text='Require students to provide property owner email/property information'),
        ),
    ]
