# Generated by Django 5.0.2 on 2025-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_survey_email_validation_survey_require_property_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysection',
            name='color',
            field=models.CharField(default='#818cf8', help_text='Hex color code for section styling', max_length=7),
        ),
    ]
