# Generated by Django 5.0.2 on 2025-11-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_surveysection_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this response was moved to trash', null=True),
        ),
    ]
