# Generated by Django 5.0.2 on 2025-11-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_surveyresponse_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_outsider',
            field=models.BooleanField(default=False, help_text='True if user signed up independently (not through school registration)'),
        ),
    ]
