# Generated by Django 5.0.2 on 2025-11-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_is_outsider'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='password_setup_token',
            field=models.CharField(blank=True, help_text='Token for password setup after approval', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='password_setup_token_expires',
            field=models.DateTimeField(blank=True, help_text='Expiration time for password setup token', null=True),
        ),
    ]
