# Generated by Django 5.2.8 on 2025-11-18 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_surveyresponse_password_setup_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('survey', 'Survey'), ('user', 'User Account'), ('property', 'Property'), ('student', 'Student'), ('response', 'Survey Response')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('item_data', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('permanent_delete_at', models.DateTimeField()),
                ('is_permanently_deleted', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_items', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash_logs', to='core.school')),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
