# Generated by Django 5.0.2 on 2025-11-29 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_userprofile_profile_picture_room_roomimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingassignment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='core.room'),
        ),
    ]
