# Generated by Django 5.2.8 on 2025-11-30 13:45

from django.db import migrations, models


def clear_empty_phones(apps, schema_editor):
    """Set duplicate empty phone values to NULL"""
    UserProfile = apps.get_model('core', 'UserProfile')
    # Find all profiles with empty or duplicate phones and set to NULL
    profiles = UserProfile.objects.filter(phone='').values_list('id', flat=True)
    if profiles:
        UserProfile.objects.filter(id__in=profiles).update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_conversation_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(clear_empty_phones),
    ]
