# Generated by Django 5.0.2 on 2025-11-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_student_school'),
        ('core', '0016_fix_phone_uniqueness'),
    ]

    operations = [
    ]
