# Generated by Django 5.0.2 on 2025-12-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_school_phone_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='boarding_key',
            field=models.CharField(blank=True, help_text='Unique key for students to join this room', max_length=50, null=True, unique=True),
        ),
    ]
