# Generated by Django 5.2.8 on 2025-12-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_room_boarding_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='boarding_address',
            field=models.TextField(blank=True, help_text='Complete address for boarding house'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='boarding_barangay',
            field=models.CharField(blank=True, help_text='Barangay for boarding house location', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='boarding_city',
            field=models.CharField(blank=True, help_text='City/Municipality for boarding house location', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='boarding_province',
            field=models.CharField(blank=True, help_text='Province for boarding house location', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='boarding_region',
            field=models.CharField(blank=True, help_text='Region for boarding house location', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
