# Generated by Django 5.2.9 on 2025-12-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_profile_picture_and_boarding_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='recipient_type',
            field=models.CharField(choices=[('students', 'Students Only'), ('owners', 'Property Owners Only'), ('both', 'Both Students & Owners')], default='students', help_text='Who should receive this survey', max_length=20),
        ),
    ]
