# Generated by Django 5.2.9 on 2025-12-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_survey_recipient_type'),
    ]

    operations = [
    ]
